### ISSUE TITLE
[Your Nodeshells] lost its sort and is showing html entities

### ISSUE THREAD

**Issue by raincomplex** [everything2/everything2#2810]
possibly related to #2594

**Comment by jaybonci** [comment]
This ended up being a longer fix. So titles in the database are saved as HTML-encoded entities; I was double-encoding them in the new display engine, which is not ideal but fine. There's huge classes of problems there, but I have to ignore this legacy behavior for right now.

Your Nodeshells got joined with [Your Nodeshells II] to consolidate functionality. II had sort by title, which didn't work quite right because of the utf8 collation, so I made an adjustment to sort them alphabetically which I think will be closer to usable. It used to be by node_id/database default sort which is not a guaranteed behavior. If the index ever kind of changed it'd be different.

At any rate, this fix should make it more consistent.

**Comment by jaybonci** [comment]
Fixed by commit #2820
