### ISSUE TITLE
Link on 'New Writeups' notelet not working as intended

### ISSUE THREAD

**Issue by andycyca** [everything2/everything2#3003]
User lostcauser wrote under the node `Q & A`. The New Writeups notelet holds a URL directing to the address: `https://everything2.com/title/Q%20%26%20A?author_id=1992599#lostcauser`

On clicking it, the site redirects me to the 'Q' node, although the address bar shows `https://everything2.com/title/Q%20%26%20A?author_id=1992599#lostcauser` which apparently should be correct.

If I try to reach the writeup from lostcauser's writeups, I arrive at the URL `https://everything2.com/title/Q+%2526+A?author_id=1992599#lostcauser` (or that's the one displaying on my browser) which is subtly different.

This is probably not a big issue, but maybe something to keep in mind as a writer?

**Comment by popisms** [comment]
This is the double URL encoding issue where spaces are treated weirdly for some reason.

`https://everything2.com/title/Q%20%2526%20A` - works
`https://everything2.com/title/Q%2520%2526%2520A` - works
`https://everything2.com/title/Q%20%26%20A` - doesn't work because the "&" is not double URL encoded

I believe that requiring the double URL encoding is the real bug, but I guess I never really looked at why it was implemented this way.

**Comment by jaybonci** [comment]
I believe this was fixed with #3004, but I'm going to add a seeds entry with an Ampersand to be able to test it more thoroughly.

**Comment by jaybonci** [comment]
Not fixed, but it is the double-encoding issue as @popisms suggests. Fixed
